### ISSUE TITLE
Password Validation required_without

### ISSUE THREAD

**Issue by ellalderton** [nodes-php/backend#147]
In the UserValidator should the password validation where we have 'required_without:id' also have 'nullable' in the array?
As at the moment (in Laravel 5.5) even when the password is empty and the id is present the other validations in the array are still run (i.e. min:8 etc). So at the moment the user cannot be updated unless the password is being changed at the same time.

**Comment by JustinBusschau** [comment]
Feel free to submit a PR - we cn expedite a review and release cycle
