### ISSUE TITLE
Middlewaregroups not loaded => Won't persist sessions

### ISSUE THREAD

**Issue by nielsiano** [nodes-php/backend#24]
Since _Laravel 5.2_ the default middlewares such as **StartSession**, **ShareErrorsFromSession** etc is not in the global stack anymore. They are now split up in middlewareGroups in the **Http\Kernel**. Meaning that, we now have an array of web-middlewares and one of api-middlewares as shown here: https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php#L25 (Which makes the middleware handling for api/web more flexible)

Which means, that the backend routeGroups needs to be wrapped in the webMiddleware for the sessions to be persisted OR that we add the middlewares back in the global stack along with the **CheckForMaintenanceMode**.

**Comment by Casperhr** [comment]
Fixed in next version
