### ISSUE TITLE
Add fav icons

### ISSUE THREAD

**Issue by Casperhr** [nodes-php/backend#53]
- Make sure some standard fav icons is added to the package, and published along

**Comment by rtrzebinski** [comment]
Where should I take these fav icons from?

**Comment by Casperhr** [comment]
We still don't have fav icons setup and base.blade.php using it.

@dennishn can you give us a jpg 256x256 of the logo there is only a svg

**Comment by dennishn** [comment]
[nstack_favicons 3.zip](https://github.com/nodes-php/backend/files/588732/nstack_favicons.3.zip)

@Casperhr Here we go. I created a .ico for you and the original is included as well.

**Comment by joscdk** [comment]
@dennishn @Casperhr shouldn't it be the blue logo from the Backend instead of NStack?

**Comment by rasmusebbesen** [comment]
in that case I need a collegue proficient in image processing to provide it in all these formats https://github.com/nodes-cloud/nstack/tree/master/public/favicons - Otherwise I will simply copy the setup from nstack

**Comment by Casperhr** [comment]
blue logo please
