### ISSUE TITLE
Typo in scss file, when gulp build , unexpected "+"

### ISSUE THREAD

**Issue by tomserowka** [nodes-php/backend#87]
Error in plugin 'sass'
Message:
    bower_components/eonasdan-bootstrap-datetimepicker/src/sass/_bootstrap-datetimepicker.scss
Error: Invalid CSS after "...id transparent;": expected "}", was "+                  "
        on line 271 of bower_components/eonasdan-bootstrap-datetimepicker/src/sass/_bootstrap-datetimepicker.scss

**Comment by krislm** [comment]
@tomserowka the dependency has been fixed. If you update the package it should work now
